Automatically generate news snippets for pull requests
conda/infrastructure pull request #703
Opened 2023-02-27 20:13 UTC by beeankha

Connected to https://github.com/conda/infrastructure/issues/673

Some design concerns/adjacent work:
- [ ] We need to standardize how news snippets are named and what content populates them
- [ ] Make sure an existing news snippet can’t be replaced by conda-bot 
- [ ] Who can activate this command?

2023-02-27 20:14 UTC, beeankha commented on .github/workflows/news.yml
> +      #     echo -e "  * <news item>">> $file_name
Kept this commented-out bit in here just for initial reference; this will all be deleted in a future commit.

2023-03-01 15:18 UTC, kenodegard requested changes

2023-03-01 15:18 UTC, kenodegard commented on .github/workflows/news.yml
> +            * <news item>
Since we already have the template can we duplicate that file instead of replicating it here?

2023-08-22 17:01 UTC, beeankha commented
Closing this PR, please see [this comment on the original issue](https://github.com/conda/infrastructure/issues/673#issuecomment-1688588090) for details.

2023-08-22 17:01 UTC, closed without merging