Label changes
conda/infrastructure pull request #720
Opened 2023-03-06 21:57 UTC by kalawac

### Description

Resolves issue #701 by renaming `sprint` label to `in-progress` and removing reference to sprint in description. Also includes change to readme to update the board names to remove reference to Sprint board and include Support and Kanban project boards.

Potential downstream concerns: 
- Kanban project board filter will need to include the new label
- There are additional references to sprints in "How We Use GitHub" that may need discussion re: whether we keep them or not.

2023-03-06 22:42 UTC, kenodegard requested changes

2023-03-06 22:42 UTC, kenodegard commented on .github/global.yml
>    color: "ededed"
We also want to add "sprint" as an alias so the old label will be automatically renamed for us

2023-03-06 23:26 UTC, kenodegard requested changes
There are also some remaining references to "sprint" in the `HOW_WE_USE_GITHUB.md` document, can you take a glance there and update as needed?

2023-03-07 17:27 UTC, kalawac commented
> There are also some remaining references to "sprint" in the `HOW_WE_USE_GITHUB.md` document, can you take a glance there and update as needed?

Updated. The name of the Kanban board will need to be updated to be in line with the updated document, but I don't have permissions.

2023-03-07 17:35 UTC, kenodegard commented
> > There are also some remaining references to "sprint" in the `HOW_WE_USE_GITHUB.md` document, can you take a glance there and update as needed?
> 
> Updated. The name of the Kanban board will need to be updated to be in line with the updated document, but I don't have permissions.

Done ✅

2023-03-13 15:47 UTC, jezdez approved these changes

2023-03-13 16:19 UTC, kenodegard approved these changes

2023-03-13 16:20 UTC, merged