Fix typo in CLA workflow file
conda/infrastructure pull request #833
Opened 2023-10-10 19:06 UTC by beeankha

2023-10-10 19:15 UTC, kenodegard requested changes
Before this gets merged we need to make the spelling correction in conda/actions, do a release, and then update the version number on line 22.

2023-10-10 19:24 UTC, kenodegard requested changes
Since we're fixing spelling errors I also see that we've misspelled perspective (perpective) in the feature issue template, lets correct that as well.

See https://github.com/conda/actions/pull/128 & https://results.pre-commit.ci/run/github/439449276/1696869192.SPP-AIKcTcOS_P1vJtGIUw

2023-10-10 19:38 UTC, beeankha commented
>Since we're fixing spelling errors I also see that we've misspelled perspective (perpective) in the feature issue template, lets correct that as well.

Done!

2023-10-11 15:48 UTC, kenodegard approved these changes

2023-10-11 15:49 UTC, merged